package:
  name: rclone
  version: "1.75.0"
  epoch: 9
  description: Rclone syncs your files to cloud storage
  copyright:
    - license: MIT
  dependencies:
    runtime:

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 9ee9d0a0cafd5e5fe3b271d2280b090ab6e64048
      repository: https://github.com/rclone/rclone
      tag: v${{package.version}}

  - uses: go/build
    with:
      ldflags: -X github.com/rclone/rclone/fs.Version=${{package.version}}
      packages: .
      output: rclone

environment:
  contents:
    repositories:
      - https://packages.wolfi.dev/os
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
