name: "Build single melange package"
description: "Builds a single package using melange"

inputs:
  melange-config-file:
    description: "Path to melange config file"
    required: true
    default: "melange.yaml"
  build-arch:
    description: "The architecture(s) to build the package for (comma separated)"
    required: true
    default: "x86_64"
  cache-dir:
    description: "The directory to store build cache files in"
    required: true
    default: "./.cache/"
  out-dir:
    description: "The directory to output built packages into"
    required: true
    default: "./packages/"
  signing-key:
    description: "The private key used to sign the built packages (PEM format)"
    required: true
  package-namespace:
    description: "The distro that this package is for (wolfi, alpine3.24, etc.)"
    required: true
    default: "unknown"

runs:
  using: "composite"

  steps:
    - name: Get package info
      id: pkg-info
      uses: rbrownwsws/get-melange-package-info@3bbdcad7aafc515f2aef9e26340dbeafd0fbf84b

    - name: Cache - Restore build deps
      uses: actions/cache/restore@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
      with:
        path: ${{ inputs.cache-dir }}
        key: ${{ steps.pkg-info.outputs.package-name }}-${{ steps.pkg-info.outputs.package-version }}-r${{ steps.pkg-info.outputs.package-epoch }}
        restore-keys: |
          ${{ steps.pkg-info.outputs.package-name }}-${{ steps.pkg-info.outputs.package-version }}-
          ${{ steps.pkg-info.outputs.package-name }}-

    - name: Build package
      shell: bash
      env:
        CACHE_DIR: "${{ inputs.cache-dir }}"
        OUT_DIR: "${{ inputs.out-dir }}"
        ARCH:  "${{ inputs.build-arch }}"
        SIGNING_KEY: "${{ inputs.signing-key }}"
        MELANGE_CONFIG_FILE: "${{ inputs.melange-config-file }}"
      run: |
        set -e

        mkdir -p "${OUT_DIR}"
        mkdir -p "${CACHE_DIR}"

        # Copy the melange config to the output dir so it will be saved with the
        # rest of the build artifacts.
        cp "${MELANGE_CONFIG_FILE}" "${OUT_DIR}/melange.yaml"

        # Get a temporary file to store the private signing key
        SIGNING_KEY_FILE=$(mktemp --tmpdir="${RUNNER_TEMP}" --suffix=.rsa)

        # Make sure we delete the private signing key file at the end of this step
        trap 'rm -f "${SIGNING_KEY_FILE}"' EXIT

        # Put the private signing key into a file
        chmod 600 "${SIGNING_KEY_FILE}"
        echo -n "${SIGNING_KEY}" > "${SIGNING_KEY_FILE}"

        # Store the public signing key in the output dir so it will be saved with
        # the rest of the build artifacts.
        openssl rsa -in "${SIGNING_KEY_FILE}" -pubout -out "${OUT_DIR}/signing.rsa.pub"

        # Do the actual build
        melange \
          build \
          --cache-dir="${CACHE_DIR}" \
          --out-dir="${OUT_DIR}" \
          --arch="${ARCH}" \
          --signing-key="${SIGNING_KEY_FILE}" \
          "${MELANGE_CONFIG_FILE}"

    - name: Cache - Save build deps
      uses: actions/cache/save@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
      with:
        path: ${{ inputs.cache-dir }}
        key: ${{ steps.pkg-info.outputs.package-name }}-${{ steps.pkg-info.outputs.package-version }}-r${{ steps.pkg-info.outputs.package-epoch }}
