name: "Get melange package info"
description: "Get information about a melange package"

inputs:
  melange-config-file:
    description: "Path to melange config file"
    required: true
    default: "melange.yaml"
  package-distro:
    description: "The distro that this package is for (will try to autodetect if unset)"
    required: false

outputs:
  package-name:
    description: "Package name"
    value: ${{ steps.pkg-info.outputs.package-name }}
  package-version:
    description: "Package version"
    value: ${{ steps.pkg-info.outputs.package-version }}
  package-epoch:
    description: "Package epoch"
    value: ${{ steps.pkg-info.outputs.package-epoch }}
  package-fullname:
    description: "Package fullname"
    value: ${{ steps.pkg-info.outputs.package-fullname }}
  package-fullversion:
    description: "Package fullversion"
    value: ${{ steps.pkg-info.outputs.package-fullversion }}
  package-distro:
    description: "Package distro"
    value: ${{ steps.pkg-info.outputs.package-distro }}

runs:
  using: "composite"

  steps:
    - name: Get melange package info
      id: pkg-info
      shell: bash
      env:
        MELANGE_CONFIG_FILE: ${{ inputs.melange-config-file }}
        PACKAGE_DISTRO: ${{ inputs.package-distro }}
      run: |
        set -euo pipefail

        chmod +x "${GITHUB_ACTION_PATH}/get-package-info.sh"
        "${GITHUB_ACTION_PATH}/get-package-info.sh"
