# $schema: https://json.schemastore.org/github-workflow.json
name: Check - Build

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    uses: rbrownwsws/melange-workflows/.github/workflows/build.yaml@72a1098a8bffaac69817dc3b81062184e112305b # v1.0.6
    with:
      build-arch: "amd64,arm64"
