# $schema: https://json.schemastore.org/github-workflow.json
name: Check - Build

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    uses: rbrownwsws/melange-workflows/.github/workflows/build.yaml@370d5dfc160f96d79c94ab58ba8c2e2914662e44 # v1.0.9
    with:
      build-arch: "amd64,arm64"
