# $schema: https://json.schemastore.org/github-workflow.json
name: Check - Build

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    uses: rbrownwsws/melange-workflows/.github/workflows/build.yaml@06853f71cd45bf2626b9dd2622a87637b78220a2 # v1.0.8
    with:
      build-arch: "amd64,arm64"
