# $schema: https://json.schemastore.org/github-workflow.json
name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    uses: rbrownwsws/melange-workflows/.github/workflows/build.yaml@2fe8e54c5f7728b295cfad67df5a17ad37c3c134 # master
    with:
      build-arch: "amd64,arm64"
