# $schema: https://json.schemastore.org/github-workflow.json
name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    uses: rbrownwsws/melange-workflows/.github/workflows/build.yaml@ac1c0cec44c71ea69d9b3245ab2184bb49881d07 # master
    with:
      build-arch: "amd64,arm64"
