# $schema: https://json.schemastore.org/github-workflow.json
name: Release

on:
  workflow_dispatch:

jobs:
  release:
    uses: rbrownwsws/melange-workflows/.github/workflows/release.yaml@9c5d28b36d35087982dd30f019fd9b2339cceca1 # master
    with:
      build-arch: "amd64,arm64"
      signing-key-name: ${{ vars.APK_SIGNING_KEY_NAME }}
      publish-release: false
      releaser-app-client-id: ${{ vars.RELEASER_APP_CLIENT_ID }}
    secrets:
      signing-key: ${{ secrets.APK_SIGNING_KEY }}
      releaser-app-private-key: ${{ secrets.RELEASER_APP_PRIVATE_KEY }}
    permissions:
      id-token: write
      attestations: write
      artifact-metadata: write
