# $schema: https://json.schemastore.org/github-workflow.json
name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - "*-r[0-9]+"

permissions: {}

jobs:
  release:
    uses: rbrownwsws/melange-workflows/.github/workflows/release.yaml@ea177c7f7882e5f8b547a0910ad0337c5c0bb73e # master
    with:
      build-arch: "amd64,arm64"
      signing-key-name: ${{ vars.APK_SIGNING_KEY_NAME }}
      publish-release: true
      releaser-app-client-id: ${{ vars.RELEASER_APP_CLIENT_ID }}
    secrets:
      signing-key: ${{ secrets.APK_SIGNING_KEY }}
      releaser-app-private-key: ${{ secrets.RELEASER_APP_PRIVATE_KEY }}
    permissions:
      contents: read            # to check out source to build
      id-token: write           # to get ID needed to sign attestation
      attestations: write       # to store attestation
      artifact-metadata: write  # to store attestation
