# $schema: https://json.schemastore.org/github-workflow.json
name: Update Package

on:
  workflow_dispatch:
  schedule:
    - timezone: "Europe/London"
      cron: '0 0 * * *'

permissions: {}

jobs:
  update:
    permissions:
      contents: read   # to get source to build

    uses: rbrownwsws/melange-workflows/.github/workflows/update-package.yaml@06853f71cd45bf2626b9dd2622a87637b78220a2 # v1.0.8
    with:
      build-arch: 'amd64,arm64'
      updater-app-client-id: ${{ vars.UPDATER_APP_CLIENT_ID }}
    secrets:
      updater-app-private-key: ${{ secrets.UPDATER_APP_PRIVATE_KEY }}
