# $schema: https://json.schemastore.org/github-workflow.json
name: Update Package Repo

on:
  workflow_dispatch:
  release:
    types:
      - released

permissions: {}

jobs:
  update-package-repo:
    permissions:
      contents: read   # to get packages from Releases
      pages: write     # to deploy to Pages
      id-token: write  # to verify the deployment originates from an appropriate source

    uses: rbrownwsws/melange-workflows/.github/workflows/update-package-repo.yaml@06853f71cd45bf2626b9dd2622a87637b78220a2 # v1.0.8
    with:
      signing-key-name: ${{ vars.APK_SIGNING_KEY_NAME }}
    secrets:
      signing-key: ${{ secrets.APK_SIGNING_KEY }}
