name: Update Repo

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Setup melange
        uses: chainguard-dev/actions/setup-melange@fabe4ed3f66ceb5f8ec86ed7ae6d0c945ca362fb # v1.6.28

      - name: Create package repo
        uses: rbrownwsws/create-melange-package-repo@4b71dfc9d2393df0df6283d6be5a979b6131fa25
        with:
          repo-dir: "./packages/"
          signing-key: ${{ secrets.APK_SIGNING_KEY }}

      - name: Upload repo as artifact
        id: deployment
        uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9 # v5.0.0
        with:
          path: "./packages/"

  deploy:
    needs: build

    runs-on: ubuntu-24.04

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128 # v5.0.0
